version: '3.8'

services:
  luminisbot:
    image: ghcr.io/luminis-gaming/luminisbot:latest
    container_name: luminisbot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres:15-alpine
    container_name: luminisbot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: luminisbot
      POSTGRES_USER: luminisbot
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # Watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: luminisbot_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Check for updates every 5 minutes (300 seconds)
      WATCHTOWER_POLL_INTERVAL: 300
      # Only update containers with the label
      WATCHTOWER_LABEL_ENABLE: true
      # Clean up old images
      WATCHTOWER_CLEANUP: true
      # Enable notifications (optional)
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL:-}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  postgres_data:
