-- Auto-generated by Luminisbot Companion App
-- This file is automatically updated by the companion app for real-time event syncing
-- DO NOT EDIT MANUALLY

LuminisbotCompanionData = {
    events = {},
    lastUpdate = 0,
    timestamp = 0
}
